#!/usr/bin/env python3
"""USPTO Patent Search — Setup Wizard.

One command to get everything ready:
    python3 get_started.py

This script:
1. Creates a Python virtual environment (.venv) if one doesn't exist
2. Installs required dependencies (requests, python-dotenv)
3. Prompts for each API key, shows a masked preview
4. Saves keys to a .env file (git-ignored)

Zero external dependencies — uses only the Python standard library.
Safe to re-run anytime to update keys or reinstall dependencies.
"""

import getpass
import os
import subprocess
import sys
from pathlib import Path

PROJECT_ROOT = Path(__file__).resolve().parent
VENV_DIR = PROJECT_ROOT / ".venv"
ENV_FILE = PROJECT_ROOT / ".env"
REQUIREMENTS = PROJECT_ROOT / "requirements.txt"

KEYS = [
    {
        "var": "USPTO_ODP_API_KEY",
        "label": "USPTO Open Data Portal (ODP) API Key",
        "url": "https://data.uspto.gov/myodp",
        "note": "Covers: ODP File Wrapper, PTAB, Assignments, Legacy Office Action APIs",
    },
    {
        "var": "PATENTSVIEW_API_KEY",
        "label": "PatentsView PatentSearch API Key",
        "url": "https://patentsview.org/apis/keyrequest",
        "note": "Covers: Patent search by inventor, assignee, keyword, CPC, citations",
    },
]


# ── Virtual environment & dependencies ────────────────────────────────

def get_venv_python() -> Path:
    """Return the path to the Python executable inside .venv."""
    if sys.platform == "win32":
        return VENV_DIR / "Scripts" / "python.exe"
    return VENV_DIR / "bin" / "python3"


def ensure_venv():
    """Create the virtual environment if it doesn't exist."""
    venv_python = get_venv_python()
    if venv_python.exists():
        return
    print("Creating virtual environment (.venv)...")
    subprocess.run(
        [sys.executable, "-m", "venv", str(VENV_DIR)],
        check=True,
    )
    print("  Done.\n")


def ensure_dependencies():
    """Install dependencies from requirements.txt into the venv."""
    venv_python = get_venv_python()
    if not REQUIREMENTS.exists():
        return

    # Quick check: try importing the packages inside the venv
    check = subprocess.run(
        [str(venv_python), "-c", "import requests; import dotenv"],
        capture_output=True,
    )
    if check.returncode == 0:
        return  # already installed

    print("Installing dependencies...")
    subprocess.run(
        [str(venv_python), "-m", "pip", "install", "-q", "-r", str(REQUIREMENTS)],
        check=True,
    )
    print("  Done.\n")


# ── API key configuration ─────────────────────────────────────────────

def mask(value: str) -> str:
    """Return a masked version of a key, showing only first 3 and last 3 chars."""
    if len(value) <= 8:
        return value[:2] + "****" + value[-1:]
    return value[:3] + "****" + value[-3:]


def read_existing_env() -> dict:
    """Read existing .env file into a dict. Returns empty dict if not found."""
    values = {}
    if not ENV_FILE.exists():
        return values
    with open(ENV_FILE, "r") as f:
        for line in f:
            line = line.strip()
            if not line or line.startswith("#"):
                continue
            if "=" in line:
                k, _, v = line.partition("=")
                k = k.strip()
                v = v.strip().strip("'").strip('"')
                if v:
                    values[k] = v
    return values


def write_env(values: dict) -> None:
    """Write key-value pairs to .env file."""
    lines = [
        "# USPTO Patent Search - API Keys",
        "# Generated by get_started.py — DO NOT commit this file.",
        "",
    ]
    for key_info in KEYS:
        var = key_info["var"]
        val = values.get(var, "")
        lines.append(f'{var}="{val}"')
    lines.append("")  # trailing newline
    with open(ENV_FILE, "w") as f:
        f.write("\n".join(lines))
    # Restrict file permissions so only the owner can read/write
    os.chmod(ENV_FILE, 0o600)


def prompt_for_keys():
    """Interactively prompt for API keys and save to .env."""
    print("-" * 60)
    print("  API Key Configuration")
    print("-" * 60)
    print()

    existing = read_existing_env()
    if existing:
        print(f"Found existing .env with {len(existing)} key(s).")
        print("Press Enter to keep an existing value, or paste a new key to replace it.")
        print()

    values = dict(existing)  # start from existing

    for key_info in KEYS:
        var = key_info["var"]
        print(f"--- {key_info['label']} ---")
        print(f"  Get yours free at: {key_info['url']}")
        print(f"  {key_info['note']}")

        current = existing.get(var)
        if current:
            print(f"  Current value: {mask(current)}")
            prompt = f"  {var} [Enter to keep]: "
        else:
            prompt = f"  {var}: "

        try:
            user_input = getpass.getpass(prompt).strip()
        except (EOFError, KeyboardInterrupt):
            print("\n\nSetup cancelled.")
            sys.exit(1)

        if user_input:
            values[var] = user_input
            print(f"  -> Set to: {mask(user_input)}")
        elif current:
            print(f"  -> Kept existing value")
        else:
            print(f"  -> Skipped (not set)")
        print()

    # Write .env
    write_env(values)
    print(f"Saved to: {ENV_FILE}")
    print()

    # Summary
    print("API Key Status:")
    all_set = True
    for key_info in KEYS:
        var = key_info["var"]
        val = values.get(var)
        if val:
            print(f"  {var}: OK ({mask(val)})")
        else:
            print(f"  {var}: MISSING")
            all_set = False

    return all_set


# ── Main ──────────────────────────────────────────────────────────────

def main():
    print("=" * 60)
    print("  USPTO Patent Search — Setup Wizard")
    print("=" * 60)
    print()

    # Step 1: Virtual environment
    ensure_venv()

    # Step 2: Dependencies
    ensure_dependencies()

    # Step 3: API keys
    all_set = prompt_for_keys()

    print()
    if all_set:
        venv_python = get_venv_python()
        print("Setup complete! Verifying keys...\n")
        verify_script = PROJECT_ROOT / "scripts" / "uspto_client.py"
        subprocess.run([str(venv_python), str(verify_script)])
    else:
        print("Some keys are missing. You can re-run this wizard anytime:")
        print("  python3 get_started.py")


if __name__ == "__main__":
    main()
